root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/planus-api ./cmd/server"
bin = "./bin/planus-api"
include_ext = ["go","tpl","tmpl","html"]
exclude_dir = ["assets","tmp","bin"]

[color]
main = "yellow"
