basePath: /
definitions:
  model.User:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  response.WelcomeResponse:
    properties:
      mensagem:
        type: string
      timestamp:
        type: string
    type: object
info:
  contact: {}
  description: This is the API documentation for the Planus application.
  title: Planus API
  version: "1.0"
paths:
  /:
    get:
      description: Returns a welcome message
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.WelcomeResponse'
      summary: Welcome
      tags:
      - App
  /user/{id}:
    get:
      description: Returns a user by ID
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Find User
      tags:
      - User
swagger: "2.0"
